# Generated by Django 5.2.5 on 2026-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_user_district_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivities",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
