# Generated by Django 5.2.5 on 2026-01-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_useractivities_balance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useractivities",
            old_name="balance",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="useractivities",
            old_name="username",
            new_name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useractivities",
            name="user_phone",
            field=models.ForeignKey(
                db_column="user_phone",
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_act",
                to=settings.AUTH_USER_MODEL,
                to_field="phone",
            ),
            preserve_default=False,
        ),
    ]
