# Generated by Django 5.2.5 on 2026-01-18 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_balance_useractivities_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivities",
            name="user_phone",
        ),
        migrations.AlterField(
            model_name="useractivities",
            name="user",
            field=models.ForeignKey(
                db_column="user_phone",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_act",
                to=settings.AUTH_USER_MODEL,
                to_field="phone",
            ),
        ),
    ]
