# Generated by Django 5.2.5 on 2026-01-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_useractivities_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivities",
            name="video_file_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
