# Generated by Django 5.2.5 on 2026-01-20 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_user_image_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="users/image.png", upload_to="media/users/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(default="0", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
