# Generated by Django 5.2.5 on 2026-01-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_user_image_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="users/image.png", upload_to="users/"),
        ),
    ]
