# Generated by Django 5.2.5 on 2026-01-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="users/image.png", upload_to="media/users/"
            ),
        ),
    ]
